---
- name: Install net-tools
  hosts: test
  become: true

  tasks:
   - name: swapoff
     command: swapoff -a
     command: "pvcreate /dev/sdc"
     command: "vgcreate swap /dev/sdc"
     command: "lvcreate -l 100%FREE -n swap swap"
     command: "sed 's#/dev/mapper/swap-swap#/dev/mapper/swap-swap#1' /etc/fstab"
     command: "mkswap /dev/mapper/swap-swap"
     command: "swapon /dev/mapper/swap-swap"
     
