---
# Master Playbook To Install and Configure Bind

- name: Install Bind
  import_playbook: bind_plays/bind_install.yml         
        
- name: Configure Bind
  import_playbook: bind_plays/bind_named_config.yml

- name: Create Zones
  import_playbook: bind_plays/bind_zone_create.yml

- name: Open Firewall For DNS
  import_playbook: bind_plays/bind_firewall.yml

- name: Restart Bind Services
  import_playbook: bind_plays/bind_restart.yml
