---
- name: Install and Configure Apache
  hosts: apache
  become: yes
  gather_facts: no
  tasks:
    - block:
      - name: Install Base Apache and Mod_SSL
        vars:
          packages:
            ['httpd','mod_ssl']
        yum:
          name: "{{ item }}"
          state: latest
        with_items: "{{ packages }}"
        register: install_result
      - name: debug result
        debug:
          var: install_result.changed
 
    - block:
      - name: Enable and Start The service
        service:
          name: httpd
          enabled: true
          state: started
        register: service_enabled_started
    - name: Debug Enabled and Started
      debug:
        var: service_enabled_started.changed

- name: Run Template
  hosts: apache
  become: yes
  gather_facts: no
  vars:
    DocumentRoot: "/var/www/html/"
    ServerName: "chadrbean.com"
    ServerAlias: "www.chadrbean.com"
    website: "chadrbean.com"
  tasks:
    - name: Render Template
      template:
        dest: /etc/httpd/conf.d/website.conf
        src: virtual_host_basic80.j2
        force: yes
        owner: apache
        mode: 0600

- name: Update Firewall To Include Port 80
  hosts: apache
  become: yes
  gather_facts: no
  tasks:
    - name: firewalld update port 80
      vars:
        services:
          ['http', 'https']
      firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
      with_items:
        - http
        - https
