---
- name: Deploy Virtual Machine from template in content library
  var_files
    - /mnt/git/_ansible-vault/vault-pass.yml
  vmware_content_deploy_template:
    hostname: '192.168.1.100'
    username: 'administrator.vcsa.local'
    password: '{{ password }}'
    template: rhel_test_template
    datastore: Shared_NFS_Volume
    folder: vm
    datacenter: Sample_DC_1
    name: Sample_VM
    resource_pool: test_rp
    validate_certs: False
    state: present
  delegate_to: localhost
    